/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_appsync_graphqlEndpoint": "https://jgwnaf33tbhe3gxyuz2mwymxqy.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-numar6einfb4vi5t73vmgoglee",
    "aws_cognito_identity_pool_id": "eu-central-1:e05d66d6-9893-4144-80cb-33a7fe2a6992",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_X9vrtJkcZ",
    "aws_user_pools_web_client_id": "37cucosllueuck7bftknaschum",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS",
            "REQUIRES_UPPERCASE"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "b-energy-storage-bc4a88a691116-staging",
    "aws_user_files_s3_bucket_region": "eu-central-1"
};


export default awsmobile;
